Algoritmo "Teste  portugol exerc 6"

Var
 num1,num2, soma,diferenca,produto: inteiro


Inicio
escreval ("digite um numero")
leia (num1)
escreval ("digite o segundo numero")
leia (num2)
soma <- num1 + num2
diferenca <- num1 - num2
produto <- num1 * num2
escreval ("seu resultado é", soma)
escreval ("seu resultado é", diferenca)
escreval ("seu resultado é", produto)




Fimalgoritmo